import os

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
HEALTHBAR_WIDTH = 50
HEALTHBAR_HEIGHT = 6
HEALTHBAR_OFFSET_Y = -50
HEALTH_NUMBER_OFFSET_Y = -50
SCALING = 1.5
RESOURCE_PATH = os.path.dirname(os.path.abspath(__file__)) + "/resources/"
SCREEN_TITLE = "Zombie Shooter"